#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Set the apc.shm_size to 160 megabytes if it has not yet been sent.
[[ -z $OPENSHIFT_PHP_APC_SHM_SIZE ]] && {
  echo "160M" > ~/.env/user_vars/OPENSHIFT_PHP_APC_SHM_SIZE
}
